'use client';
import { use, useEffect, useRef, useState } from 'react';
import { Expand, Users, CheckCircle2, MapPin, Timer } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Notice, LiveStatus } from '@/components/feedback';
import QrCodeDisplay from '@/components/QrCodeDisplay';
import { api, useResource, useAttendanceRealtime } from '@/lib/client-api';
import type { EventDetail } from '@/types';
import { DataSkeleton, LoadingStatus, RefreshStatus } from '@/components/loading';
import { generateTotpToken, getTotpCycleInfo } from '@/lib/totp';
interface Token {token:string;timestamp:number;expiresAt:number;secret?:string}
export default function Projector({params}:{params:Promise<{eventId:string}>}) {
  const {eventId}=use(params);const {data,error,refresh,isLoading,isRefreshing}=useResource<EventDetail>(`/api/events/${eventId}?view=summary`);const live=useAttendanceRealtime(`event_id=eq.${eventId}`,refresh);
  const [current,setCurrent]=useState<Token|null>(null);const [remaining,setRemaining]=useState(0);const [tokenError,setTokenError]=useState('');const frame=useRef<HTMLDivElement>(null);
  useEffect(()=>{let active=true;let retry:ReturnType<typeof setTimeout>|undefined;let secret:string|null=null;
    const load=async()=>{try{const result=await api<Token>(`/api/events/${eventId}/totp`, undefined, 'GET', {background:true});if(!active)return;secret=result.secret!;setTokenError('');}catch{if(active){setTokenError('การเชื่อมต่อขัดข้อง');retry=setTimeout(load,2000);}}};
    const ticker=setInterval(()=>{if(!active||!secret)return;const now=Date.now();const info=getTotpCycleInfo();setCurrent({token:generateTotpToken(secret,now),timestamp:now,expiresAt:now+info.remainingMs,secret});setRemaining(info.remainingMs);},100);void load();
    return()=>{active=false;clearInterval(ticker);clearTimeout(retry);};
  },[eventId]);
  const rate=data?.stats.totalStudents?Math.round(data.stats.attendedCount/data.stats.totalStudents*100):0;
  return <div ref={frame} className="overflow-auto rounded-3xl bg-background p-1 sm:p-6"><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">ARU · Event check-in</p><h1 className="mt-2 text-2xl font-bold sm:text-4xl">{data?.event.name||'กำลังโหลดกิจกรรม...'}</h1><p className="mt-3 text-sm text-muted-foreground">เปิดกิจกรรมในบัญชีนักศึกษา แล้วเลือก “สแกนหน้าจอโปรเจคเตอร์”</p></div><Button variant="outline" aria-label="สลับโหมดเต็มจอ" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void frame.current?.requestFullscreen().catch(()=>setTokenError('เบราว์เซอร์ไม่รองรับโหมดเต็มจอ'));}}><Expand/>เต็มจอ</Button></div><Notice text={error}/><RefreshStatus active={isRefreshing}/>{isLoading&&<DataSkeleton label="กำลังโหลดสถิติกิจกรรม…" cards/>}<div className="grid gap-7 lg:grid-cols-[1.1fr_1fr]"><Card className="flex flex-col items-center py-8 text-center"><div className="mb-4 flex items-center gap-2 rounded-full bg-primary/7 px-4 py-2 text-sm font-bold text-primary"><Timer size={16}/>QR เปลี่ยนทุก 5 วินาที</div><div className="qr-box flex min-h-[330px] w-full max-w-[360px] items-center justify-center">{current&&remaining>0?<QrCodeDisplay value={JSON.stringify({e:eventId,c:current.token,t:current.timestamp})} size={310}/>:<LoadingStatus label={tokenError||'กำลังเปลี่ยน QR Code…'}/>}</div><div className="mt-5 h-1.5 w-full max-w-xs overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-gold" style={{width:`${remaining/5000*100}%`}}/></div><p className="mt-3 text-xs text-muted-foreground">เปลี่ยนรหัสใน {Math.ceil(remaining/1000)} วินาที</p><p className="mt-6 flex items-center gap-2 text-xs text-muted-foreground"><MapPin size={14}/>เปิด GPS และอยู่ในรัศมี {data?.event.radius_meters||100} เมตร</p></Card><div className="flex flex-col gap-5"><Card className="flex-1"><LiveStatus connected={live}/><p className="mt-8 flex items-center gap-2 text-sm text-muted-foreground"><CheckCircle2 className="size-5 text-green-700"/>ยืนยันการเข้าร่วมแล้ว</p><p className="my-3 text-7xl font-bold tracking-tight text-primary sm:text-8xl">{data?.stats.attendedCount??'…'}<span className="ml-3 text-xl text-muted-foreground">คน</span></p><p className="mt-5 flex items-center gap-2 text-sm text-muted-foreground"><Users size={17}/>จากผู้มีสิทธิ์ {data?.stats.totalStudents??'…'} คน</p><div className="mt-8 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{width:`${rate}%`}}/></div><p className="mt-3 text-right text-sm font-bold text-gold">{rate}% ของผู้มีสิทธิ์</p></Card><Card className="border-[#ead9b7] bg-[#fcf6e8]"><h2 className="font-bold">สแกนไม่สำเร็จ?</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">เปิด “แสดง QR Code ของฉัน” แล้วติดต่อทีมงาน<br/>เพื่อยืนยันการเข้าร่วมที่จุดลงทะเบียน</p></Card></div></div></div>;
}
