'use client';
import { useState } from 'react';
import { ScanLine, Search, Users, CheckCircle2, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card } from '@/components/ui/card';
import { PageHeading, Notice, LiveStatus } from '@/components/feedback';
import QrScannerModal from '@/components/QrScannerModal';
import { api, errorText, useResource, useAttendanceRealtime } from '@/lib/client-api';
import type { Event, EventDetail, Registration } from '@/types';
export default function StaffPage() {
  const {data,error}=useResource<{events:Event[]}>('/api/events');const [selected,setSelected]=useState('');const id=selected||data?.events[0]?.id;
  return <><PageHeading eyebrow="Staff portal" title="เช็คอินหน้างาน" description="ตรวจสอบตัวตนนักศึกษา แล้วสแกนบัตรหรือค้นหารหัสเพื่อยืนยันการเข้าร่วม"/><Notice text={error}/><label className="mb-6 max-w-lg">กิจกรรมที่ปฏิบัติงาน<select value={id||''} onChange={e=>setSelected(e.target.value)}>{!data?.events.length&&<option value="">ยังไม่มีกิจกรรม</option>}{data?.events.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label>{id&&<StaffEvent key={id} id={id}/>}</>;
}
function StaffEvent({id}:{id:string}) {
  const {data,error,refresh}=useResource<EventDetail>(`/api/events/${id}`);const live=useAttendanceRealtime(`event_id=eq.${id}`,refresh);
  const [scan,setScan]=useState(false);const [busy,setBusy]=useState(false);const [query,setQuery]=useState('');const [message,setMessage]=useState('');const [failure,setFailure]=useState('');const [candidate,setCandidate]=useState<Registration|null>(null);
  const checkIn=async(body:object)=>{setScan(false);setBusy(true);setFailure('');setMessage('');try{const result=await api<{message:string}>('/api/checkin/staff',{eventId:id,...body});setMessage(result.message);setCandidate(null);await refresh();}catch(e){setFailure(errorText(e));}finally{setBusy(false);}};
  const results=data?.registrations.filter(r=>query.trim()&&`${r.users?.username} ${r.users?.full_name}`.toLowerCase().includes(query.trim().toLowerCase())).slice(0,20)||[];
  return <><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="flex items-center gap-2 text-sm"><Users size={17} className="text-gold"/>เข้าร่วมแล้ว <strong>{data?.stats.attendedCount||0}</strong> / {data?.stats.totalStudents||0} คน</p><LiveStatus connected={live}/></div><Notice text={failure||error}/><Notice text={message} success/><div className="grid gap-6 lg:grid-cols-2"><Card className="flex flex-col items-center justify-center py-12 text-center"><div className="mb-6 rounded-2xl bg-primary/7 p-6 text-primary"><ScanLine size={52}/></div><h2 className="text-xl font-bold">สแกน QR ของนักศึกษา</h2><p className="my-4 max-w-sm text-sm leading-7 text-muted-foreground">ให้นักศึกษาเปิด “แสดง QR Code ของฉัน”<br/>ตรวจสอบตัวตนก่อนสแกนยืนยันการเข้าร่วม</p><Button disabled={busy} onClick={()=>setScan(true)}><ScanLine/>{busy?'กำลังเช็คอิน...':'เปิดกล้องสแกน'}</Button><p className="mt-6 flex items-center gap-1 text-xs text-muted-foreground"><ShieldCheck size={14}/>ทีมงานยืนยันตัวบุคคลได้โดยไม่ใช้ GPS</p></Card><Card><h2 className="flex items-center gap-2 text-lg font-bold"><Search size={20} className="text-gold"/>ค้นหาและเช็คอินด้วยมือ</h2><p className="my-3 text-xs leading-6 text-muted-foreground">สำหรับกรณีแบตเตอรี่หมด กล้องเสีย หรือไม่สามารถเปิดบัตรได้</p><Input aria-label="ค้นหานักศึกษา" placeholder="รหัสนักศึกษาหรือชื่อ–นามสกุล" value={query} onChange={e=>{setQuery(e.target.value);setCandidate(null);}}/><div className="mt-4 max-h-80 divide-y divide-border overflow-y-auto">{results.map(r=><div key={r.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-bold">{r.users?.full_name}</p><p className="mt-1 text-xs text-muted-foreground">{r.users?.username}</p></div>{r.is_attended?<span className="text-xs text-green-700">เช็คอินแล้ว</span>:<Button size="sm" variant="outline" disabled={busy} onClick={()=>setCandidate(r)}>เลือก</Button>}</div>)}{query&&!results.length&&<p className="py-8 text-center text-sm text-muted-foreground">ไม่พบรายชื่อในกิจกรรมนี้</p>}</div>{candidate&&<div className="mt-5 rounded-xl border border-[#ead9b7] bg-[#fcf6e8] p-4"><p className="text-sm font-bold">ยืนยันตัวตน: {candidate.users?.full_name}</p><p className="mt-2 text-xs leading-6">รหัส {candidate.users?.username}<br/>โปรดตรวจสอบบัตรนักศึกษาหรือเอกสารประจำตัวก่อนกดยืนยัน</p><Button className="mt-4 w-full" disabled={busy} onClick={()=>void checkIn({method:'MANUAL',username:candidate.users?.username})}><CheckCircle2/>{busy?'กำลังบันทึก...':'ยืนยันเช็คอินด้วยมือ'}</Button></div>}</Card></div><QrScannerModal isOpen={scan} onScanSuccess={qr=>void checkIn({method:'STAFF_SCAN',qr})} onClose={()=>setScan(false)}/></>;
}
